version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    labels:
      - "actions"
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    labels:
      - "pip"
      - "dependencies"
